# Generated by Django 5.0.2 on 2024-08-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_number', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('committee', models.TextField()),
                ('position', models.TextField()),
                ('attendance', models.BooleanField()),
            ],
        ),
    ]
