# Generated by Django 5.0.2 on 2024-07-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='committee',
        ),
        migrations.AlterField(
            model_name='student',
            name='committee',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
