# Generated by Django 5.0.2 on 2024-07-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_position_committee_alter_student_committee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
